// Source: terms-of-service_2.md, privacy-policy_2.md,
// data-storage-notice_1.md (verified by size + md5 before import).
// Wording is copied exactly as supplied - do not edit, shorten or
// reword it. This revision has no square-bracketed placeholders left.

export const legalDocuments = {
  terms: {
    tabLabel: "Terms of Service",
    title: "Terms of Service",
    lastUpdated: "Last updated: 2 October 2026",
    blocks: [
      { type: 'paragraph', text: "These Terms of Service (\"Terms\") are an agreement between you and The Clarity Project Ltd (\"we\", \"us\", \"our\"), a company registered in England and Wales under number 12817337, with its registered office at 30 Francis Green Lane, Penkridge, Stafford, England, ST19 5HF. They govern your use of The Clarity Portal, the website and tools at portal.theclarityproject.co.uk (the \"Portal\"). Please read them carefully. By ticking the box when you create your account, or by using the Portal, you agree to them." },
      { type: 'heading', text: "1. What the Portal is" },
      { type: 'paragraph', text: "The Portal is a set of self-directed planning, decision-making, reflection and wellbeing tools for leaders and teams, including daily and meeting planners, a personal operating plan, decision tools, reviews and journals, and breathing exercises. It is provided as a personal development resource. It is not a substitute for professional advice (see section 6)." },
      { type: 'heading', text: "2. Who can use the Portal" },
      { type: 'paragraph', text: "You must be at least 18 years old and able to enter a binding contract. If you use the Portal on behalf of an organisation, you confirm that you are authorised to do so. We may refuse or end access where we reasonably believe these Terms have been broken." },
      { type: 'heading', text: "3. Your account" },
      { type: 'paragraph', text: "You must give us accurate information when you sign up, including your name, a working email address and a mission statement, and keep it up to date. You must confirm your email address before you can use your account." },
      { type: 'paragraph', text: "You are responsible for keeping your password confidential and for everything done through your account. Choose a strong password that you do not use anywhere else. Tell us promptly at tim@theclarityproject.co.uk if you think someone else has accessed your account. You may hold only one account unless we agree otherwise." },
      { type: 'heading', text: "4. Your content" },
      { type: 'paragraph', text: "\"Your Content\" means everything you enter into the Portal, including your mission, plans, decisions, reflections, journal entries and settings." },
      {
        type: 'list',
        items: [
          "You own Your Content. We do not claim ownership of it.",
          "You give us a limited, non-exclusive, worldwide, royalty-free licence to store, process, display and back up Your Content, only so far as needed to run the Portal for you, keep it secure and meet our legal duties. This licence ends when Your Content is deleted, subject to the backup period explained in our Data Storage Notice.",
          "You are responsible for Your Content. You promise that you have the right to enter it and that it does not break the law or anyone else's rights.",
          "Please do not enter confidential information that belongs to your employer or a third party unless you are permitted to. Do not enter other people's sensitive personal information (for example health details) about them.",
          "How we handle personal data is explained in our Privacy Policy and Data Storage Notice, which form part of this agreement.",
        ],
      },
      { type: 'heading', text: "5. Acceptable use" },
      { type: 'paragraph', text: "You must not:" },
      {
        type: 'list',
        items: [
          "use the Portal for anything unlawful, harmful, abusive, harassing, defamatory or discriminatory;",
          "try to gain unauthorised access to the Portal, other accounts, our systems or our data;",
          "introduce viruses or other harmful code, or interfere with the Portal's operation or security;",
          "probe, scan or test the Portal for vulnerabilities without our written permission;",
          "copy, scrape, harvest or extract data from the Portal by automated means, or build a competing service from it;",
          "reverse engineer, decompile or attempt to extract the source code of the Portal, except where the law allows it;",
          "resell, sublicense or commercially exploit the Portal without our written agreement;",
          "use the Portal in a way that places an unreasonable load on our systems; or",
          "let anyone else use your account.",
        ],
      },
      { type: 'heading', text: "6. Not professional advice" },
      { type: 'paragraph', text: "The Portal and everything in it, including the tools, prompts, examples, breathing exercises and any content we publish, is for general information, reflection and personal development only." },
      {
        type: 'list',
        items: [
          "It is not medical, psychological, psychiatric, therapeutic, legal, financial, tax or other professional advice, and it does not create a coaching, counselling, clinical or professional relationship between you and us unless we have agreed that separately in writing.",
          "The breathing exercises are general relaxation techniques. Do not use them if they cause you discomfort, dizziness or distress, and stop if you feel unwell. Speak to a qualified health professional before relying on them if you have a medical condition, are pregnant, or are unsure.",
          "You are responsible for your own decisions. Tools such as decision frameworks help you structure your thinking. They do not tell you what to decide, and we do not guarantee any outcome from using them.",
          "If you are in crisis or worried about your safety or someone else's, please do not use the Portal. In an emergency call 999. In the UK you can contact the Samaritans on 116 123 (free, 24 hours) or your GP or NHS 111.",
        ],
      },
      { type: 'heading', text: "7. Availability and changes to the Portal" },
      { type: 'paragraph', text: "We aim to keep the Portal available and working well, but we provide it \"as is\" and \"as available\". We do not promise that it will be uninterrupted, error-free or secure at all times. We may carry out maintenance, and may add, change, suspend or remove features at any time. If we make a change that materially reduces what you can do, we will give reasonable notice where we can. Please keep your own copy of anything important to you." },
      { type: 'heading', text: "8. Our intellectual property" },
      { type: 'paragraph', text: "The Portal, including its design, text, graphics, logos, tools, templates, software and the \"The Clarity Project\" and \"The Clarity Portal\" names, belongs to us or our licensors and is protected by intellectual property laws. We give you a personal, non-exclusive, non-transferable, revocable licence to use the Portal for your own personal and professional development in line with these Terms. All rights not expressly given to you are reserved." },
      { type: 'paragraph', text: "If you send us feedback or suggestions, you agree that we may use them freely without paying you or crediting you." },
      { type: 'heading', text: "9. Fees" },
      { type: 'paragraph', text: "At the time of these Terms, the Portal is free to use. If we introduce or change charges, we will tell you in advance and you will not be charged unless you agree." },
      { type: 'heading', text: "10. Suspension and ending your account" },
      { type: 'paragraph', text: "You can stop using the Portal and delete your account at any time from the My Account page. Deleting your account permanently deletes your data as described in our Data Storage Notice." },
      { type: 'paragraph', text: "We may suspend or end your access, with notice where reasonable, if you seriously or repeatedly break these Terms, if we are required to by law, or if we stop providing the Portal. If we end your access without it being your fault, we will give you reasonable notice and a chance to take a copy of Your Content where we can." },
      { type: 'paragraph', text: "Sections that by their nature should survive (including sections 4, 8, 11, 12 and 14) continue after your account ends." },
      { type: 'heading', text: "11. Our responsibility to you" },
      { type: 'paragraph', text: "Nothing in these Terms limits or excludes our liability for death or personal injury caused by our negligence, for fraud or fraudulent misrepresentation, or for anything else that cannot be limited or excluded by law. If you are a consumer, your statutory rights are not affected by these Terms." },
      { type: 'paragraph', text: "Subject to that:" },
      {
        type: 'list',
        items: [
          "we are not liable for any loss that was not a reasonably foreseeable result of our breach, or that you could have avoided by taking reasonable steps;",
          "we are not liable for loss of profit, revenue, business, goodwill or anticipated savings, or for any indirect or consequential loss, to the extent the law allows this exclusion;",
          "we are not responsible for decisions you make or actions you take in reliance on the Portal, or for loss of or damage to data caused by events outside our reasonable control or by your own actions; and",
          "our total liability to you arising out of or in connection with the Portal, whether in contract, tort (including negligence), breach of statutory duty or otherwise, is limited to \u00a3100 or, if greater, the total fees you paid us in the 12 months before the claim arose.",
        ],
      },
      { type: 'paragraph', text: "If you are using the Portal for business purposes, you also agree that we are not liable to you for any loss arising from your use of the Portal for those purposes beyond the limits above." },
      { type: 'heading', text: "12. Changes to these Terms" },
      { type: 'paragraph', text: "We may update these Terms, for example to reflect changes in the law or in the Portal. If a change is significant we will tell you by email or in the Portal before it takes effect, and where the law requires it we will ask you to accept the new Terms. If you do not agree to a change, you can delete your account before it takes effect. If you carry on using the Portal after the change takes effect, you accept the updated Terms." },
      { type: 'heading', text: "13. Complaints and concerns" },
      { type: 'paragraph', text: "If you have a concern or complaint, please write to us at tim@theclarityproject.co.uk and we will respond within a reasonable time, normally within 14 days. If you have a complaint about how we handle personal data, please see the Privacy Policy." },
      { type: 'heading', text: "14. General" },
      {
        type: 'list',
        items: [
          "**Whole agreement.** These Terms, together with the Privacy Policy and the Data Storage Notice, are the whole agreement between you and us about the Portal and replace any earlier discussions about it.",
          "**If part is unenforceable.** If a court finds any part of these Terms unenforceable, the rest stays in force.",
          "**No waiver.** If we do not enforce a right straight away, that does not mean we have given it up.",
          "**Transfer.** You may not transfer your rights or duties under these Terms without our written consent. We may transfer ours to a successor of our business, and we will tell you if we do.",
          "**Events outside our control.** We are not in breach of these Terms, and not liable for any delay or failure, caused by events outside our reasonable control.",
          "**Third parties.** No one other than you and us has any right to enforce these Terms under the Contracts (Rights of Third Parties) Act 1999.",
          "**Governing law.** These Terms, and any dispute or claim arising out of or in connection with them or the Portal (including non-contractual disputes), are governed by the law of England and Wales, and the courts of England and Wales have exclusive jurisdiction. If you are a consumer living in Scotland or Northern Ireland, you may also bring proceedings in the courts of the part of the UK where you live, and if you live elsewhere you keep any mandatory consumer rights of your home country.",
        ],
      },
      { type: 'heading', text: "15. Contact us" },
      { type: 'paragraph', text: "The Clarity Project Ltd\nCompany number 12817337\n30 Francis Green Lane, Penkridge, Stafford, England, ST19 5HF\nEmail: tim@theclarityproject.co.uk" },
    ],
  },
  privacy: {
    tabLabel: "Privacy Policy",
    title: "Privacy Policy",
    lastUpdated: "Last updated: 2 October 2026",
    blocks: [
      { type: 'paragraph', text: "This Privacy Policy explains how The Clarity Project Ltd (\"we\", \"us\", \"our\"), collects, uses, shares and protects your personal data when you use The Clarity Portal at portal.theclarityproject.co.uk (the \"Portal\"). It also explains your rights. We are committed to handling your data lawfully, fairly and transparently, in line with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018." },
      { type: 'paragraph', text: "Please read this together with our Data Storage Notice, which explains in more detail where and how your data is stored and protected, and our Terms of Service." },
      { type: 'heading', text: "1. Who is responsible for your data" },
      { type: 'paragraph', text: "We are the \"controller\" of your personal data. Our details are:" },
      { type: 'paragraph', text: "The Clarity Project Ltd\n30 Francis Green Lane, Penkridge, Stafford, England, ST19 5HF\nCompany number: 12817337\nPrivacy contact: tim@theclarityproject.co.uk" },
      { type: 'heading', text: "2. The data we collect" },
      { type: 'paragraph', text: "**Information you give us when you create and use your account:**" },
      {
        type: 'list',
        items: [
          "your first name, last name and email address;",
          "your password (we never see it in readable form: it is protected by our authentication provider and stored only in scrambled, or \"hashed\", form);",
          "your mission statement;",
          "a record that you accepted our Terms of Service, Privacy Policy and Data Storage Notice, and the date and time you did so;",
          "the content you create in the Portal, including daily and meeting plans, personal operating plans, decisions and decision-tool answers, reflections, reviews, journal entries, and your breathing and display settings; and",
          "anything you send us when you contact us.",
        ],
      },
      { type: 'paragraph', text: "**Information we collect automatically:**" },
      {
        type: 'list',
        items: [
          "your IP address, and the approximate location (such as country, region and time zone) worked out from it, which we use to show you the right time and greeting and to help keep the Portal secure;",
          "technical information such as your browser type, device type, operating system, language and the pages or features you use; and",
          "log and security information, such as when you log in, failed login attempts and error reports.",
        ],
      },
      { type: 'paragraph', text: "**Information we receive from others:** we do not buy personal data about you or receive it from data brokers." },
      { type: 'heading', text: "3. Sensitive information you may choose to write" },
      { type: 'paragraph', text: "The Portal includes reflective tools and a journal. We do not ask you for information about your health, but what you write is up to you, and it could reveal things such as how you are feeling, stress or anxiety, or other details the law treats as \"special category\" data." },
      { type: 'paragraph', text: "If you choose to enter special category data, we process it only on the basis of your explicit consent, which you give by choosing to enter it. You can withdraw that consent at any time by deleting the entry or your account. You never have to enter this kind of information to use the Portal, and we ask you not to enter sensitive information about other people." },
      { type: 'heading', text: "4. How and why we use your data" },
      { type: 'paragraph', text: "We use your personal data only where the law allows. These are the purposes and the legal bases we rely on:" },
      {
        type: 'list',
        items: [
          "**To create and run your account and provide the Portal** (including sign-up, email confirmation, login, saving your content, and showing it back to you). Legal basis: performing our contract with you (Article 6(1)(b) UK GDPR).",
          "**To send service messages**, such as email confirmation, password resets and important notices about your account or these documents. Legal basis: performing our contract with you, and our legitimate interest in keeping you informed about the service you use.",
          "**To keep the Portal secure and prevent misuse or fraud**, including monitoring failed logins and investigating problems. Legal basis: our legitimate interests in protecting our service and users (Article 6(1)(f)).",
          "**To personalise basics such as the time-of-day greeting and local time.** Legal basis: our legitimate interest in making the Portal work properly for you.",
          "**To maintain and improve the Portal**, such as fixing faults and understanding which features work well. Legal basis: our legitimate interests in running and improving our service. We keep this to the minimum we need and do not use the content of your journals or reflections for this purpose.",
          "**To keep a record of your agreement to our terms.** Legal basis: our legitimate interest in being able to show what you agreed to, and the need to establish, exercise or defend legal claims.",
          "**To comply with the law** and respond to lawful requests from courts, regulators or law enforcement. Legal basis: legal obligation (Article 6(1)(c)).",
          "**To handle any special category data you choose to enter.** Legal basis: your explicit consent (Article 9(2)(a)).",
        ],
      },
      { type: 'paragraph', text: "We do not use your personal data for advertising or marketing to third parties, we do not sell it, and we do not make decisions about you using fully automated processing that has legal or similarly significant effects. We will not send you marketing emails unless you have chosen to receive them." },
      { type: 'heading', text: "5. Who we share your data with" },
      { type: 'paragraph', text: "We share personal data only with the organisations that help us run the Portal (\"processors\"), and only so far as needed. They may use it only on our instructions, and we have agreements with them that require them to protect it." },
      {
        type: 'list',
        items: [
          "**Supabase** provides our database, authentication and storage, where your account and content are stored.",
          "**Vercel** hosts the Portal and delivers it to your browser.",
          "**Resend** sends the emails we send to you, such as confirmation and password-reset emails.",
          "**ipapi.co** receives your IP address so that it can tell us your approximate location and time zone.",
        ],
      },
      { type: 'paragraph', text: "We may also disclose your data where we are required to by law or court order, to protect the rights, property or safety of us or others, or in connection with a sale or reorganisation of our business (in which case the new owner must continue to protect your data in line with this policy). We do not sell, rent or trade your data." },
      { type: 'heading', text: "6. Transfers outside the UK" },
      { type: 'paragraph', text: "Some of these providers process data outside the UK, including in the United States and the European Economic Area. Where we transfer personal data outside the UK, we make sure it is protected, for example by relying on a UK adequacy decision, or on approved safeguards such as the UK International Data Transfer Agreement or the UK Addendum to the EU Standard Contractual Clauses, together with any additional steps needed. You can contact us for more information about the safeguards we use." },
      { type: 'heading', text: "7. How long we keep your data" },
      { type: 'paragraph', text: "We keep your data only as long as we need it." },
      {
        type: 'list',
        items: [
          "**Your account and content** are kept while your account is open. When you delete your account, your data is permanently deleted from our live systems straight away, and remains in encrypted backups only until they are overwritten.",
          "**Records of your agreement to our terms** and security logs may be kept for up to 6 years after your account closes where we need them to deal with legal claims or protect our service.",
          "**Emails to us** are kept for as long as needed to deal with your query and for a reasonable period afterwards.",
        ],
      },
      { type: 'heading', text: "8. Cookies and similar technologies" },
      { type: 'paragraph', text: "We use only the cookies and browser storage that are strictly necessary to run the Portal, for example to keep you logged in securely, to remember your session and to remember settings such as your preferred theme. These do not need your consent under UK law. We do not use advertising or tracking cookies, and we do not use analytics cookies. If we ever add anything that needs your consent, we will ask you first and update this policy. You can clear or block cookies and site storage in your browser settings, but the Portal may then stop working properly." },
      { type: 'paragraph', text: "The chat button in the Portal opens WhatsApp or iMessage with a ready-written message to us. If you choose to send it, that message is handled by WhatsApp or Apple under their own terms and privacy policies, not through the Portal." },
      { type: 'heading', text: "9. Keeping your data secure" },
      { type: 'paragraph', text: "We use appropriate technical and organisational measures to protect your data, including encryption of data while it travels between your device and the Portal, encryption at rest by our database provider, access controls, and secure development and deployment practices. No system is completely secure, so we cannot guarantee absolute security, and you share responsibility for it: please use a strong, unique password and keep it private. If a data breach is likely to put you at risk, we will tell you and the Information Commissioner's Office (ICO) as the law requires. More detail is in our Data Storage Notice." },
      { type: 'heading', text: "10. Your rights" },
      { type: 'paragraph', text: "Under data protection law you have the right to:" },
      {
        type: 'list',
        items: [
          "**be informed** about how we use your data (this policy);",
          "**access** a copy of the personal data we hold about you;",
          "**correct** data that is inaccurate or incomplete (you can edit most of it yourself in My Account);",
          "**erase** your data (you can delete your account in My Account, or ask us to);",
          "**restrict** how we use your data in certain circumstances;",
          "**data portability**: to receive the data you provided in a structured, commonly used, machine-readable format, and to ask us to send it to another organisation where possible;",
          "**object** to our use of your data where we rely on legitimate interests; and",
          "**withdraw consent** at any time where we rely on consent, without affecting what we did before you withdrew it.",
        ],
      },
      { type: 'paragraph', text: "To use any of these rights, email tim@theclarityproject.co.uk. We may need to check your identity first. We will normally respond within one month, and we may extend that by up to two further months for complex requests, telling you why. There is normally no charge, though we may charge a reasonable fee or refuse a request that is manifestly unfounded or excessive. These rights are not absolute and some have exceptions, which we will explain if they apply." },
      { type: 'heading', text: "11. Complaints" },
      { type: 'paragraph', text: "We would like the chance to put things right, so please contact us first at tim@theclarityproject.co.uk. You also have the right to complain to the UK's data protection regulator, the Information Commissioner's Office, at ico.org.uk or on 0303 123 1113." },
      { type: 'heading', text: "12. Children" },
      { type: 'paragraph', text: "The Portal is for adults aged 18 and over. We do not knowingly collect personal data from anyone under 18. If you believe a child has given us personal data, please contact us and we will delete it." },
      { type: 'heading', text: "13. Links to other sites" },
      { type: 'paragraph', text: "The Portal may link to other websites. We are not responsible for their privacy practices. Please read their policies before you give them any personal data." },
      { type: 'heading', text: "14. Changes to this policy" },
      { type: 'paragraph', text: "We may update this policy from time to time. If we make a material change we will tell you by email or in the Portal before it takes effect. The date at the top shows when it was last updated." },
      { type: 'heading', text: "15. Contact us" },
      { type: 'paragraph', text: "For any question about this policy or your data, contact us at tim@theclarityproject.co.uk or by post at 30 Francis Green Lane, Penkridge, Stafford, England, ST19 5HF." },
    ],
  },
  dataStorage: {
    tabLabel: "Data Storage Notice",
    title: "Data Storage Notice",
    lastUpdated: "Last updated: 2 October 2026",
    blocks: [
      { type: 'paragraph', text: "The Clarity Portal holds some very personal information: your plans, decisions, reflections and journal. This notice explains in plain English where that information is kept, who can reach it, how it is protected, how long it stays, and how you can have it removed. It forms part of our agreement with you alongside the Terms of Service and the Privacy Policy, which has the full legal detail about your rights." },
      { type: 'paragraph', text: "The Clarity Project Ltd is responsible for your data." },
      { type: 'heading', text: "1. What we store" },
      {
        type: 'list',
        items: [
          "**Your account:** first name, last name, email address, and your sign-in credentials (your password is stored only in scrambled, \"hashed\" form and we cannot read it).",
          "**Your mission:** the mission statement shown at the top of the Portal.",
          "**What you create:** daily and meeting plans, your personal operating plan, decisions and the answers you enter into decision tools, reflections and reviews, journal entries, and your names for these items.",
          "**Your settings:** such as your breathing preferences and display choices.",
          "**Your agreement:** a record that you accepted our terms, and when.",
          "**Technical data:** your IP address, approximate location and time zone, and basic log information (see the Privacy Policy).",
        ],
      },
      { type: 'paragraph', text: "We do not store payment card details in the Portal." },
      { type: 'heading', text: "2. Where it is stored" },
      {
        type: 'list',
        items: [
          "**Supabase** hosts our database and authentication. Your account and content are stored there on secure cloud servers. Where your data is processed outside the UK, we rely on the safeguards described in our Privacy Policy.",
          "**Vercel** hosts the Portal website that you use in your browser. It delivers the Portal to you but your saved content lives in the database, not on the website servers.",
          "**Resend** sends our emails (for example confirmation and password-reset emails) and holds the delivery details of those emails for a limited time.",
          "**ipapi.co** is sent your IP address so that it can return your approximate location and time zone. We do not use it to store your content.",
          "**Your own device:** your browser may keep small pieces of data on your device, such as your login session and settings, so the Portal works properly. This stays on your device and you can clear it in your browser settings.",
        ],
      },
      { type: 'paragraph', text: "Some of these providers handle data outside the UK. Where they do, we rely on approved legal safeguards, as described in our Privacy Policy." },
      { type: 'heading', text: "3. How it is protected" },
      {
        type: 'list',
        items: [
          "**In transit:** all traffic between your device and the Portal is encrypted using HTTPS.",
          "**At rest:** our database provider encrypts stored data.",
          "**Access control:** your content is tied to your account, and the Portal is built so that you can only read and change your own content. You must log in to see it.",
          "**Limited staff access:** only a small number of authorised people can reach our systems, only where needed to run, secure, fix or support the Portal, and only with security controls in place. We do not browse your journal, reflections or plans. We will only look at your content if you ask us to help with a fault and agree, or if the law or a court requires us to.",
          "**Passwords:** we never store your password in readable form.",
          "**Providers:** we choose reputable providers and have agreements with them requiring them to keep your data secure and use it only on our instructions.",
          "**Testing and updates:** we keep the Portal and its software updated and review changes before they go live.",
        ],
      },
      { type: 'heading', text: "4. What we do not do" },
      {
        type: 'list',
        items: [
          "We do not sell your data.",
          "We do not use your plans, reflections or journal to show you advertising or share them with advertisers.",
          "We do not use your content to train artificial intelligence models.",
          "We do not share your content with other Portal users.",
        ],
      },
      { type: 'heading', text: "5. Backups and how long we keep things" },
      { type: 'paragraph', text: "We take regular backups so we can restore the Portal if something goes wrong. Backups are encrypted and kept for a limited period and then overwritten." },
      { type: 'paragraph', text: "While your account is open, we keep your data so that you can use it. If you delete something inside the Portal (for example a plan), it is removed from the live Portal straight away but may remain in backups until they are overwritten." },
      { type: 'heading', text: "6. Deleting your data" },
      { type: 'paragraph', text: "You are in control:" },
      {
        type: 'list',
        items: [
          "**Delete an item:** you can delete individual plans, decisions and entries inside the Portal.",
          "**Delete your account:** go to My Account and choose Delete account. This permanently deletes your account and all of your content from our live systems straight away. It cannot be undone, so please keep a copy of anything you want first. Copies in encrypted backups are overwritten within the backup period above and are not used for anything in the meantime.",
          "**Records we may keep:** we may keep a minimal record that you accepted our terms, and security logs, for a limited period where we need them to deal with legal claims or protect the Portal, as explained in the Privacy Policy.",
          "**By request:** you can also ask us to delete your data, or to give you a copy of it, by emailing tim@theclarityproject.co.uk.",
        ],
      },
      { type: 'heading', text: "7. If something goes wrong" },
      { type: 'paragraph', text: "If we discover a security breach that is likely to put your rights and freedoms at risk, we will tell you without undue delay, explain what happened and what we recommend you do, and we will report it to the Information Commissioner's Office within 72 hours where the law requires." },
      { type: 'heading', text: "8. Your part" },
      { type: 'paragraph', text: "Security works best when we both do our bit. Please:" },
      {
        type: 'list',
        items: [
          "use a strong password that you do not use elsewhere, and do not share it;",
          "log out on shared or public devices;",
          "keep your device and browser up to date; and",
          "tell us straight away at tim@theclarityproject.co.uk if you think your account has been accessed by someone else.",
        ],
      },
      { type: 'heading', text: "9. The limits of what we can promise" },
      { type: 'paragraph', text: "We work hard to protect your data, but no online service can be completely secure and we cannot promise that nothing will ever go wrong. What we do promise is to use appropriate security measures, to be honest with you if something happens, and to follow the law." },
      { type: 'heading', text: "10. Questions" },
      { type: 'paragraph', text: "If you have any questions about where your data is kept or how it is protected, email tim@theclarityproject.co.uk. Our Privacy Policy explains your full legal rights, including your right to complain to the Information Commissioner's Office (ico.org.uk, 0303 123 1113)." },
    ],
  },
};

export const legalDocumentOrder = ['terms', 'privacy', 'dataStorage'];
